apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-exercises.fullname" . }}
  labels:
    {{ include "frontend-exercises.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "frontend-exercises.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "frontend-exercises.fullname" . }}
    spec:
      containers:
        - name: frontend-exercises
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3001
          env:
            {{- range .Values.extraEnvVars }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}